from pydantic import BaseModel, EmailStr
from datetime import date

class EmployeeCreate(BaseModel):
    full_name: str
    email: EmailStr
    department: str

class EmployeeUpdate(EmployeeCreate):
    pass


class Employee(EmployeeCreate):
    id: int  # Auto-generated by DB
    class Config:
        orm_mode = True


class AttendanceCreate(BaseModel):
    employee_id: int
    date: date
    status: str
